apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: demo-registry.ap-southeast-5.cr.aliyuncs.com/sample/nodeapp:e9d7242
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: acr
